# Generated by Django 5.2.16 on 2026-07-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Mi Empresa', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
